config/routes.rb
require 'sidekiq/web'

Thing::Application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    resources :users do
      get :send_password_reset_email
    end
    resources :tracks
    resources :instructor_email_list
    resources :track_lead_email_list
    resources :backups
    resources :reports do
      collection do
        get :instructor_signin
        get :kingdom_war_points
      end
    end
  end

  namespace :coordinator do
    resources :instructables
    resources :conflicts
    resources :locations do
      collection do
        get :timesheets
        get :freebusy
      end
    end
  end

  namespace :proofreader do
    resources :instructables
  end

  get 'sitemap(.:format)' => 'sitemap#index'

  get 'about/:action' => 'about'
  get '/about' => 'about#about'
  root :to => 'about#index'

  get 'howto/:action' => 'howto', as: :howto

  devise_for :users, path: 'sessions'

  resources :users do
    resource :instructor_profile
    resources :instructables
    resource :schedule, controller: 'users/schedules'
  end

  resources :calendars
  resources :changelogs
  resources :instructors

  resources :policies do
    member do
      post 'accept'
    end
  end

end

app/views/admin/_menu_additions.html.haml
%li.nav-item.dropdown
  %a.nav-link.dropdown-toggle#adminDropdown{:href => '#', :data => {:toggle => 'dropdown'}, aria: {haspopup: "true", expanded: "false"}}
    Admin
  .dropdown-menu{aria: {labelledby: "adminDropdown"}}
    %h6.dropdown-header Database Actions
    = link_to 'Backups', admin_backups_path, class: 'dropdown-item'
    = link_to 'Database Summary', admin_tracks_path, class: 'dropdown-item'
    .dropdown-divider
    %h6.dropdown-header Reports and Forms
    = link_to 'Instructor Sign In', instructor_signin_admin_reports_path(format: :pdf), class: 'dropdown-item'
    = link_to 'Kingdom War Points', kingdom_war_points_admin_reports_path(format: :csv), class: 'dropdown-item'
    .dropdown-divider
    %h6.dropdown-header Per-day schedules
    - Instructable::CLASS_DATES.each do |date|
      = link_to "#{date} onward", calendar_path(date, format: :pdf, target: '_blank'), class: 'dropdown-item'
    .dropdown-divider
    %h6.dropdown-header Email Addresses
    = link_to 'Instructors', admin_instructor_email_list_index_path, class: 'dropdown-item'
    = link_to 'Track Leads', admin_track_lead_email_list_index_path, class: 'dropdown-item'
    .dropdown-divider
    = link_to 'Users', admin_users_path, class: 'dropdown-item'
    = link_to 'Trackless Classes', coordinator_instructables_path(track: 'No Track'), class: 'dropdown-item'