config/routes.rb
require 'sidekiq/web'

Thing::Application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    resources :users do
      get :send_password_reset_email
    end
    resources :tracks
    resources :instructor_email_list
    resources :track_lead_email_list
    resources :backups
    resources :reports do
      collection do
        get :instructor_signin
        get :kingdom_war_points
      end
    end
  end

  namespace :coordinator do
    resources :instructables
    resources :conflicts
    resources :locations do
      collection do
        get :timesheets
        get :freebusy
      end
    end
  end

  namespace :proofreader do
    resources :instructables
  end

  get 'sitemap(.:format)' => 'sitemap#index'

  get 'about/:action' => 'about'
  get '/about' => 'about#about'
  root :to => 'about#index'

  get 'howto/:action' => 'howto', as: :howto

  devise_for :users, path: 'sessions'

  resources :users do
    resource :instructor_profile
    resources :instructables
    resource :schedule, controller: 'users/schedules'
  end

  resources :calendars
  resources :changelogs
  resources :instructors

  resources :policies do
    member do
      post 'accept'
    end
  end

end

app/controllers/instructor_profiles_controller.rb
class InstructorProfilesController < ApplicationController
  skip_before_filter :check_profile

  def new
    @user.add_missing_contacts
    render action: :edit
  end

  def edit
    @user.add_missing_contacts
  end

  def update
    if @user.instructor?
      notice = 'Instructor profile updated.'
    else
      notice = 'Instructor profile created.'
    end
    @user.instructor = true
    @user.profile_updated_at = Time.now
    puts permitted_params.to_json
    if @user.update_attributes(permitted_params)
      redirect_to root_path, notice: notice
    else
      render action: :edit
    end
  end

  private

  def permitted_params
    params.require(:user).permit(
      :mundane_name, :phone_number, :sca_name, :sca_title, :phone_number_onsite,
      :kingdom, :no_contact,
      { :instructor_profile_contacts_attributes => [[ :address, :protocol, :id ]] },
      :available_days => []
     )
  end

  def current_resource
    @user ||= current_user
  end
end

app/helpers/instructor_profile_helper.rb
# encoding: utf-8

module InstructorProfileHelper
  # Return the protocol for use in simple_form's :as parameter
  def as_for_protocol(protocol)
    InstructorProfileContact::PROTOCOL_TYPES[protocol]
  end

  # Return the placeholder text for user in simple_form's :placeholder
  # parameter
  def placeholder_for_protocol(protocol)
    type = InstructorProfileContact::PROTOCOL_TYPES[protocol]
    return 'http://www.example.com/' if type == :url
    'user@example.com' if type == :email
  end
  
  def mailto_link_for_instructable(instructable)
    '&lt;'.html_safe + mail_to(instructable.user.email, nil, subject: "Pennsic University: #{instructable.name}") + '&gt;'.html_safe
  end
end

app/views/instructor_profiles/edit.html.haml
- create_or_update = current_user.instructor? ? 'Update' : 'Create'
- title "#{create_or_update} Instructor Profile"

= simple_form_for current_user, url: user_instructor_profile_path(current_user) do |f|
  %fieldset
    %legend Name and Required Contact Information
    = f.input :mundane_name, label: 'Legal name', placeholder: 'Full name'
    = f.input :sca_title, label: 'SCA title', hint: 'SCA title, if any', collection: User::TITLES, label_method: :titleize
    = f.input :sca_name, label: 'SCA name', hint: 'SCA name, up to 30 characters, without title', input_html: { maxlength: 30 }
    = f.input :kingdom, label: 'SCA kingdom', hint: 'SCA kingdom, if any', collection: User::KINGDOMS, label_method: :titleize
    = f.input :phone_number, placeholder: '+1 405.555.1212', hint: 'Pre-pennsic contact number.  This number will only be used by Pennsic staff should you need to be contacted.'
    = f.input :phone_number_onsite, placeholder: '+1 405.555.1212', hint: 'Cell or other on site contact number.  This number will only be used by Pennsic staff should you need to be contacted.'
    %p.alert.alert-info
      Please select the days you plan on being on site and available to
      teach classes.  These will be used by default for classes you
      request, although you can override them on a per-class basis.
      Actual class days are more limited than the selection below.
    = f.input :available_days, as: :check_boxes, checked: current_user.available_days, collection: Instructable::PENNSIC_DATES, label: false

  = f.button :submit, "#{create_or_update} profile", :class => 'btn btn-primary'
  = link_to 'Cancel', :back, :class => 'btn'