config/routes.rb
require 'sidekiq/web'

Thing::Application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    resources :users do
      get :send_password_reset_email
    end
    resources :tracks
    resources :instructor_email_list
    resources :track_lead_email_list
    resources :backups
    resources :reports do
      collection do
        get :instructor_signin
        get :kingdom_war_points
      end
    end
  end

  namespace :coordinator do
    resources :instructables
    resources :conflicts
    resources :locations do
      collection do
        get :timesheets
        get :freebusy
      end
    end
  end

  namespace :proofreader do
    resources :instructables
  end

  get 'sitemap(.:format)' => 'sitemap#index'

  get 'about/:action' => 'about'
  get '/about' => 'about#about'
  root :to => 'about#index'

  get 'howto/:action' => 'howto', as: :howto

  devise_for :users, path: 'sessions'

  resources :users do
    resource :instructor_profile
    resources :instructables
    resource :schedule, controller: 'users/schedules'
  end

  resources :calendars
  resources :changelogs
  resources :instructors

  resources :policies do
    member do
      post 'accept'
    end
  end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @order = params[:order]

    instructor_ids = Instructable.pluck(:user_id).uniq
    @instructors = User.where(id: instructor_ids)

    if @order == 'kingdom'
      @instructors = @instructors.order('kingdom, lower(sca_name)')
    else
      @instructors = @instructors.order('lower(sca_name)')
    end
  end
end

app/views/instructors/index.html.haml
- title 'Instructors by First Name'

%p
  - if @order == 'kingdom'
    = link_to 'By first name', instructors_path
  - else
    = link_to 'By kingdom', instructors_path(order: 'kingdom')

- letter = '*'

- @instructors.each do |i|
  - if @order == 'kingdom'
    - order_text = i.kingdom.present? ? i.kingdom.titleize : 'Unknown'
  - else
    - order_text = i.sca_name[0].upcase
  - if letter != order_text
    - letter = order_text
    %h3 -- #{letter} --
  = i.best_name
  %br